cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove'),
]

my_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.landing, name='main_page'),
    path('products/', views.product_list, name='product_list'),
    path('<str:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<str:slug>/', views.product_detail, name='product_detail')
]

cart/models.py
from django.db import models

orders/models.py
from django.db import models
from shop.models import Product


class Order(models.Model):
    first_name = models.CharField(max_length=50, verbose_name='Фамилия')
    last_name = models.CharField(max_length=50, verbose_name='Имя')
    email = models.EmailField()
    address = models.CharField(max_length=250, verbose_name='Адрес')
    postal_code = models.CharField(max_length=20, verbose_name='Почтовый индекс')
    city = models.CharField(max_length=100, verbose_name='Город')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлен')
    paid = models.BooleanField(default=False, verbose_name='Оплачен')


    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


    def __str__(self):
        return 'Order {}'.format(self.id)


    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.PROTECT)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)


    def __str__(self):
        return '{}'.format(self.id)


    def get_cost(self):
        return self.price * self.quantity

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField("Категория", max_length=150, db_index=True)
    slug = models.SlugField("URL", max_length=150, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', verbose_name="Категория", on_delete=models.SET_NULL, null=True)
    name = models.CharField("Название", max_length=200, db_index=True)
    slug = models.SlugField("URL", max_length=200, db_index=True)
    description = models.TextField("Описание")
    price = models.DecimalField("Цена", max_digits=10, decimal_places=2)
    image = models.ImageField("Фото", upload_to='media/products/', blank=True)
    stock = models.PositiveIntegerField("Склад")
    available = models.BooleanField("Активный", default=True)
    created = models.DateTimeField("Дата добавления", auto_now_add=True)
    updated = models.DateTimeField("Дата обновления", auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1,21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email',
                  'address', 'postal_code', 'city']

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            cart.clear()
            return render(request, 'orders/order/created.html', {'order': order})
    else:
        form = OrderCreateForm
    return render(request, 'orders/order/create.html', {'cart': cart, 'form': form})

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.core.paginator import Paginator


def landing(request):
    return render(request, 'shop/main_page.html')


def product_list(request, category_slug=None):
    search_query = request.GET.get('search', '')
    if search_query:
        p_list = Product.objects.filter(name__icontains=search_query)
    else:
        p_list = Product.objects.all()

    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        p_list = products.filter(category=category)
    paginator = Paginator(p_list, 20)
    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)
    is_paginated = page.has_other_pages()
    if page.has_previous():
            prev_url = '?page={}'.format(page.previous_page_number())
    else:
            prev_url = ''

    if page.has_next():
            next_url = '?page={}'.format(page.next_page_number())
    else:
            next_url = ''


    return render(request, 'shop/product/list.html', {'category': category,
                                                      'categories': categories,
                                                      'products': products,
                                                      'page_object': page,
                                                      'is_paginated': is_paginated,
                                                      'next_url': next_url,
                                                      'prev_url': prev_url
                                                      })


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'product': product,
                                                        'cart_product_form': cart_product_form})

templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}{% endblock %}
{% block content %}
<h1 class="text-center">Корзина</h1>
<table class="table table-bordered table-striped text-center">
    <thead class="thead-dark">
    <tr>
        <th>Фото</th>
        <th>Товар</th>
        <th>Количество</th>
        <th>Удалить</th>
        <th>Цена за единицу</th>
        <th>Цена</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
        {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{{ product.image.url }}" style="height: 10rem; width: 10rem">
                    </a>
                </td>
                <td>{{ product.name }}</td>
                <td>{{ item.quantity }}</td>
                <td><a href="{% url "cart:cart_remove" product.id %}">Удалить</a></td>
                <td class="num">{{ item.price }} грн.</td>
                <td class="num">{{ item.total_price }} грн.</td>
            </tr>
        {% endwith %}
    {% endfor %}
    <tr class="total">
        <td colspan="4"></td>
        <td class="text-right">Всего:</td>
        <td class="num">{{ cart.get_total_price }} грн.</td>
    </tr>
    </tbody>
</table>
<p style="padding-bottom: 3rem" class="text-right">
    <a href="{% url "shop:product_list" %}" class="btn btn-primary">Продолжить покупки</a>
    <a href="{% url "orders:order_create" %}" class="btn btn-success">Оформить заказ</a>
</p>
{% endblock %}

templates/orders/order/create.html
{% extends "shop/base.html" %}
{% block title %}{% endblock %}
{% block content %}
    <h1 class="text-center">Оформление заказа</h1>
    <div class="order-info m-3">
        <h3>Ваш заказ</h3>
        <ul>
            {% for item in cart %}
                <li>
                    {{ item.quantity }} x {{ item.product.name }}
                    <span>{{ item.total_price }} грн.</span>
                </li>
            {% endfor %}
        </ul>
        <p>Всего: {{ cart.get_total_price }} грн.</p>
    </div>
    <form action="." method="post" class="order-form m-3">
                {{ form.as_p }}
        <p style="padding-bottom: 3rem"><input type="submit" value="Заказать"></p>
        {% csrf_token %}
    </form>
{% endblock %}

templates/orders/order/created.html
{% extends "shop/base.html" %}

{% block title %}Спасибо!{% endblock %}

{% block content %}
<div class="container text-center mt-3">
    <h1>Спасибо!</h1>
    <p>Вы успешно оформили заказ. Номер вашего заказа
        <strong>{{ order.id }}</strong>.</p>
</div>
{% endblock %}

templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>{% block title %}My shop{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
    {% include 'shop/navbar.html' %}
    <div id="content">
        {% block content %}
        {% endblock %}
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    </div>
</body>
    {% include 'shop/footer.html' %}
</html>

templates/shop/footer.html
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet"/>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<footer class="footer">
  <div class="row">
    <div class="col-sm-6">
      <div class="container text-left">
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-linkedin"></i></a>
        <a href="#"><i class="fa fa-google-plus"></i></a>
        <a href="#"><i class="fa fa-skype"></i></a>
      </div>
    </div>
      <div class="col-sm-6">
        <div class="container">
        <div class="text-right" style="color: white">© 2020 Все права защищены</div>
        </div>
      </div>
    </div>
    </div>
  </div>
</footer>

templates/shop/main_page.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{% endblock %}
{% block content %}
  <div id="carouselExampleCaptions" class="carousel slide mb-5 pb-3" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img style="height: 600px; width: 100%" src="{% static 'media/main_page/111.jpg' %}" class="d-block" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5 style="font-size: xx-large; color: black;">Компьютеры и ноутбуки</h5>
        </div>
      </div>
      <div class="carousel-item">
        <img style="height: 600px; width: 100%" src="{% static 'media/main_page/222.jpg' %}" class="d-block" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5 style="font-size: xx-large; color: black;">Телефоны</h5>
        </div>
      </div>
      <div class="carousel-item">
        <img style="height: 600px; width: 100%" src="{% static 'media/main_page/333.jpg' %}" class="d-block" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5 style="font-size: xx-large; color: black;">Аксессуары</h5>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
{% endblock %}

templates/shop/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #0d4457;">
  <a style="color: white" class="navbar-brand" href="{% url 'shop:main_page' %}">Shop</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a style="color: white" class="nav-link active" href="{% url 'shop:product_list' %}">Товары</a>
      </li>
    </ul>
  </div>
</nav>
<div class="row">
  <div class="col-6">
    <form class="form-inline" action="{% url 'shop:product_list' %}">
      <input class="form-control mr-sm-2 m-2" type="search" placeholder="Найти товар" aria-label="Search" name="search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
    </form>
  </div>
  <div class="col-6">
    <div class="cart m-3 text-right">
        {% with total_items=cart|length %}
        {% if cart|length > 0 %}
        Корзина:
        <a href="{% url 'cart:cart_detail'%}">
            {{ total_items }} item{{ total_items|pluralize }},
            {{ cart.get_total_price }}
        </a>
        {% else %}
            Корзина пустая
        {% endif %}
        {% endwith %}
    </div>
  </div>
</div>

templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}{{ product.name }}{% endif %}
{% endblock %}
{% block content %}
<div class="product-detail">
    <div class="row mt-5">
        <div class="col-sm-6">
            <div style="text-align: center"><img src="{{ product.image.url }}" style="height: 25rem; width: 25rem"></div>
            <div style="padding: 3rem">{{ product.description|linebreaks }}</div>
        </div>
        <div class="col-sm-6">
            <h1>{{ product.name }}</h1>
            <h2><a href="{{ product.category.get_absolute_url }}" style="text-decoration: none;">{{ product.category }}</a></h2>
            <p class="price">{{ product.price }} грн.</p>
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
            {{ cart_product_form }}
            {% csrf_token %}
            <input type="submit" value="Добавить в корзину">
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Товары{% endif %}
{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">
            <div id="sidebar">
                <h3 style="text-align: center">Каталог товаров</h3>
                <div class="list-group">
                        <a style="text-decoration: none; color: black" href="{% url 'shop:product_list' %}"><button type="button" class="list-group-item list-group-item-action" {% if not category %}class="selected"{% endif %}>Все товары</button></a>
                    {% for c in categories %}
                        <a  style="text-decoration: none; color: black" href="{{ c.get_absolute_url }}"><button type="button" class="list-group-item list-group-item-action" {% if category.slug == c.slug %}class="selected"{% endif %}>{{ c.name }}</button></a>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div id="main" class="product-list">
                <h1 class="text-center mb-5">{% if category %}{{ category.name }}{% else %}Все товары{% endif %}</h1>
                <div class="row">
                    {% for a in page_object.object_list %}
                    <div class="col-sm-3">
                        <a style="text-decoration: none" href="{%  url 'shop:product_detail' a.id a.slug%}">
                        <div class="card mb-5" style="width: 10rem; height: 15rem">
                            <img src="{{ a.image.url }}" class="card-img-top" height="150px" alt="">
                            <div class="card-body text-dark" style="overflow: hidden">
                                <h4 class="card-title text-center" style="font-size: small">{{a.name}}</h4>
                                <p class="card-text text-center">{{ a.price }} грн.</p>
                            </div>
                        </div>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
<br>


{% if is_paginated %}
<nav aria-label="...">
    <ul class="pagination justify-content-center">
        <li class="page-item {% if not prev_url %} disabled {% endif %}">
            <a class="page-link" href="{{ prev_url }}" tabindex="-1" aria-disabled="true">Назад</a>
        </li>
        {% for n in page_object.paginator.page_range %}
        {% if page_object.number == n %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ n }}">{{ n }}<span class="sr-only">(current)</span></a>
        </li>
        {% elif n > page_object.number|add:-3 and n < page_object.number|add:3 %}
        <li class="page-item">
            <a class="page-link" href="?page={{ n }}">{{ n }}</a>
        </li>
        {% endif %}
        {% endfor %}
        <li class="page-item {% if not next_url %} disabled {% endif %}">
            <a class="page-link" href="{{ next_url }}" tabindex="-1" aria-disabled="true">Вперед</a>
        </li>
    </ul>
</nav>
{% endif %}
<br>
{% endblock %}